// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9CjZhHhvyOCNR7aSbl7kPYgw-frj-z30',
    appId: '1:670352973690:web:2814b92aab584e7896c0c3',
    messagingSenderId: '670352973690',
    projectId: 'milkmanmanager',
    authDomain: 'milkmanmanager.firebaseapp.com',
    storageBucket: 'milkmanmanager.appspot.com',
    measurementId: 'G-ZQ26C8NQEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9ahA8axYv5ehTrpfsPMBSYKmatqOYa4',
    appId: '1:670352973690:android:0b16ab315601794696c0c3',
    messagingSenderId: '670352973690',
    projectId: 'milkmanmanager',
    storageBucket: 'milkmanmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8-4juNx9kpj7L2VAnbc2XfFC0D55faE',
    appId: '1:670352973690:ios:bb0b191d567e590296c0c3',
    messagingSenderId: '670352973690',
    projectId: 'milkmanmanager',
    storageBucket: 'milkmanmanager.appspot.com',
    iosBundleId: 'com.example.milkmanManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy8-4juNx9kpj7L2VAnbc2XfFC0D55faE',
    appId: '1:670352973690:ios:bb0b191d567e590296c0c3',
    messagingSenderId: '670352973690',
    projectId: 'milkmanmanager',
    storageBucket: 'milkmanmanager.appspot.com',
    iosBundleId: 'com.example.milkmanManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9CjZhHhvyOCNR7aSbl7kPYgw-frj-z30',
    appId: '1:670352973690:web:ad34be9e59658a0596c0c3',
    messagingSenderId: '670352973690',
    projectId: 'milkmanmanager',
    authDomain: 'milkmanmanager.firebaseapp.com',
    storageBucket: 'milkmanmanager.appspot.com',
    measurementId: 'G-VBYJWEQGGM',
  );
}
